name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      
      - name: Create tfvars file
        run: |
          cat > terraform.auto.tfvars <<EOF
          vpc_name = "${{ secrets.TF_VAR_vpc_name }}"
          cidr = "${{ secrets.TF_VAR_cidr }}"
          azs = ["eu-north-1a", "eu-north-1b"]
          public_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
          private_subnets = ["10.0.11.0/24", "10.0.12.0/24"]
          enable_nat_gateway = ${{ secrets.TF_VAR_enable_nat_gateway }}
          single_nat_gateway = ${{ secrets.TF_VAR_single_nat_gateway }}
          one_nat_gateway_per_az = ${{ secrets.TF_VAR_one_nat_gateway_per_az }}
          environment = "${{ secrets.TF_VAR_environment }}"
          linux_ami = "${{ secrets.TF_VAR_linux_ami }}"
          instance_type = "${{ secrets.TF_VAR_instance_type }}"
          hosted_zone_id = "${{ secrets.TF_VAR_hosted_zone_id }}"
          domain_name = "${{ secrets.TF_VAR_domain_name }}"
          region = "${{ secrets.TF_VAR_region }}"
          EOF
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Destroy
        run: terraform destroy -auto-approve